// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {service} from '../models';
import {sshsession} from '../models';
import {security} from '../models';
import {hostkey} from '../models';
import {macro} from '../models';
import {tunnel} from '../models';
import {nettools} from '../models';
import {sftpmanager} from '../models';

export function AddFolder(arg1:string,arg2:string):Promise<model.TreeNode>;

export function AddFolderWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<model.TreeNode>;

export function AddSession(arg1:string,arg2:model.SessionProfile):Promise<model.TreeNode>;

export function AddWorkspacePane(arg1:string):Promise<model.Pane>;

export function AppendSessionLog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function BRMClassifyQuestion(arg1:string):Promise<string>;

export function BRMDetectInstallation(arg1:string):Promise<service.BRMInstallation>;

export function BRMDiagnose(arg1:service.BRMDiagnosisRequest):Promise<service.BRMDiagnosisResult>;

export function BRMDiscoverLogs(arg1:string,arg2:string):Promise<Array<service.BRMLogFile>>;

export function BRMGetErrorKnowledge(arg1:string):Promise<service.ErrorKnowledge>;

export function BRMGetOpcodeKnowledge(arg1:string):Promise<service.OpcodeInfo>;

export function BRMInspectSource(arg1:string,arg2:string,arg3:string,arg4:number):Promise<service.BRMSourceInspection>;

export function BroadcastCommand(arg1:Array<string>,arg2:string,arg3:string):Promise<service.BroadcastResult>;

export function BroadcastRaw(arg1:string):Promise<void>;

export function CancelAuthChallenge(arg1:string):Promise<void>;

export function CancelBroadcast(arg1:string):Promise<void>;

export function CheckSSHAgent():Promise<Record<string, any>>;

export function ClassifyConnectionError(arg1:string):Promise<sshsession.ClassifiedError>;

export function ClearAuditLogs():Promise<void>;

export function CloseTab(arg1:string):Promise<void>;

export function CloseWorkspacePane(arg1:string):Promise<model.Workspace>;

export function ConfigureFolder(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<model.TreeNode>;

export function DeleteKnownHost(arg1:string,arg2:number):Promise<void>;

export function DeleteMacro(arg1:string):Promise<void>;

export function DeleteNode(arg1:string):Promise<model.TreeNode>;

export function DeleteSavedPassword(arg1:string):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function DuplicateFolder(arg1:string):Promise<model.TreeNode>;

export function DuplicateSession(arg1:string):Promise<model.TreeNode>;

export function ExecuteMacro(arg1:string,arg2:Array<string>):Promise<void>;

export function ExecuteMulti(arg1:Array<string>,arg2:string):Promise<void>;

export function ExpandAllFolders(arg1:boolean):Promise<model.TreeNode>;

export function ExportAuditLogsCSV():Promise<string>;

export function ExportAuditLogsJSON():Promise<string>;

export function ExportSessions():Promise<string>;

export function ExportSessionsToFile():Promise<string>;

export function FindSessionPassword(arg1:string,arg2:string,arg3:number,arg4:string):Promise<string>;

export function FocusWorkspacePane(arg1:string):Promise<void>;

export function GetAuditLogs(arg1:number):Promise<Array<service.AuditEvent>>;

export function GetAvailableSerialPorts():Promise<Array<string>>;

export function GetCustomizerConfig():Promise<security.CustomizerConfig>;

export function GetKnownHosts():Promise<Array<hostkey.HostKeyEntry>>;

export function GetMacros():Promise<Array<macro.Macro>>;

export function GetRecentLogs(arg1:number):Promise<Array<service.LogEntry>>;

export function GetSavedPassword(arg1:string):Promise<string>;

export function GetSavedPasswords():Promise<Array<service.SavedCredential>>;

export function GetSecurityPolicy():Promise<security.SecurityPolicy>;

export function GetSessionPassphrase(arg1:string):Promise<string>;

export function GetSessionPassword(arg1:string):Promise<string>;

export function GetSessionTree():Promise<model.TreeNode>;

export function GetTunnels():Promise<Array<tunnel.TunnelConfig>>;

export function GetWorkspace():Promise<model.Workspace>;

export function HasSavedPassword(arg1:string):Promise<boolean>;

export function ImportSessions(arg1:string):Promise<model.TreeNode>;

export function ImportSessionsFromFile():Promise<model.TreeNode>;

export function IsXServerRunning():Promise<boolean>;

export function LaunchRDPSession(arg1:model.SessionProfile,arg2:string):Promise<void>;

export function LaunchSystemTool(arg1:string):Promise<void>;

export function LaunchXServer():Promise<string>;

export function MoveNode(arg1:string,arg2:string,arg3:number):Promise<model.TreeNode>;

export function MoveSession(arg1:string,arg2:string):Promise<model.TreeNode>;

export function MoveWorkspaceTab(arg1:string,arg2:string,arg3:number):Promise<model.Workspace>;

export function NetCalculateHash(arg1:string,arg2:string):Promise<string>;

export function NetLookupDNS(arg1:string):Promise<Record<string, Array<string>>>;

export function NetPing(arg1:string):Promise<string>;

export function NetPortScan(arg1:string,arg2:Array<number>):Promise<Array<nettools.PortScanResult>>;

export function OpenLocalTerminal(arg1:string):Promise<string>;

export function OpenSession(arg1:model.SessionProfile,arg2:string):Promise<string>;

export function OpenSessionLogFolder():Promise<void>;

export function OpenSessionWithTabID(arg1:string,arg2:model.SessionProfile,arg3:string):Promise<void>;

export function OpenSessionWithTabIDAndJumpSecret(arg1:string,arg2:model.SessionProfile,arg3:string,arg4:string):Promise<void>;

export function QuickConnect(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function RenameNode(arg1:string,arg2:string):Promise<model.TreeNode>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondAuthChallenge(arg1:string,arg2:Array<string>):Promise<void>;

export function RespondHostKey(arg1:string,arg2:string):Promise<void>;

export function RunSSHCommand(arg1:string,arg2:string):Promise<string>;

export function SFTPChmodLocal(arg1:string,arg2:string):Promise<void>;

export function SFTPChmodRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPCommitExternalChange(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPCreateFile(arg1:string,arg2:string):Promise<void>;

export function SFTPCreateFileLocal(arg1:string):Promise<void>;

export function SFTPDelete(arg1:string,arg2:string):Promise<void>;

export function SFTPDeleteLocal(arg1:string):Promise<void>;

export function SFTPDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPGetFileProperties(arg1:string,arg2:string):Promise<sftpmanager.SFTPItem>;

export function SFTPGetLocalDrives():Promise<Array<string>>;

export function SFTPList(arg1:string,arg2:string):Promise<service.SFTPListResult>;

export function SFTPListLocal(arg1:string):Promise<service.SFTPListResult>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPMkdirLocal(arg1:string):Promise<void>;

export function SFTPOpenExternal(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SFTPReadFile(arg1:string,arg2:string):Promise<string>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPRenameLocal(arg1:string,arg2:string):Promise<void>;

export function SFTPUpload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPWriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveCustomizerConfig(arg1:security.CustomizerConfig):Promise<void>;

export function SaveMacro(arg1:macro.Macro):Promise<void>;

export function SavePassword(arg1:string,arg2:string):Promise<void>;

export function SaveSecurityPolicy(arg1:security.SecurityPolicy):Promise<void>;

export function SaveSessionPassword(arg1:string,arg2:string):Promise<void>;

export function SaveTerminalOutput(arg1:string,arg2:string):Promise<string>;

export function SaveTunnel(arg1:tunnel.TunnelConfig):Promise<void>;

export function SelectDownloadDest(arg1:string):Promise<string>;

export function SelectPrivateKeyFile():Promise<string>;

export function SelectUploadFile():Promise<string>;

export function SetWorkspaceActiveTab(arg1:string,arg2:string):Promise<void>;

export function SetWorkspaceLayout(arg1:string):Promise<model.Workspace>;

export function StartTunnel(arg1:string,arg2:string):Promise<void>;

export function StopSessionLog(arg1:string):Promise<string>;

export function StopTunnel(arg1:string):Promise<void>;

export function ToggleFolder(arg1:string,arg2:boolean):Promise<model.TreeNode>;

export function UpdateFolder(arg1:string,arg2:string):Promise<model.TreeNode>;

export function UpdateSession(arg1:model.SessionProfile):Promise<model.TreeNode>;

export function ValidatePrivateKeyFile(arg1:string,arg2:string):Promise<sshsession.KeyInfo>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
