// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1, arg2) {
  return window['go']['main']['App']['AddFolder'](arg1, arg2);
}

export function AddFolderWithOptions(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddFolderWithOptions'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddSession(arg1, arg2) {
  return window['go']['main']['App']['AddSession'](arg1, arg2);
}

export function AddWorkspacePane(arg1) {
  return window['go']['main']['App']['AddWorkspacePane'](arg1);
}

export function AppendSessionLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendSessionLog'](arg1, arg2, arg3);
}

export function BRMClassifyQuestion(arg1) {
  return window['go']['main']['App']['BRMClassifyQuestion'](arg1);
}

export function BRMDetectInstallation(arg1) {
  return window['go']['main']['App']['BRMDetectInstallation'](arg1);
}

export function BRMDiagnose(arg1) {
  return window['go']['main']['App']['BRMDiagnose'](arg1);
}

export function BRMDiscoverLogs(arg1, arg2) {
  return window['go']['main']['App']['BRMDiscoverLogs'](arg1, arg2);
}

export function BRMGetErrorKnowledge(arg1) {
  return window['go']['main']['App']['BRMGetErrorKnowledge'](arg1);
}

export function BRMGetOpcodeKnowledge(arg1) {
  return window['go']['main']['App']['BRMGetOpcodeKnowledge'](arg1);
}

export function BRMInspectSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BRMInspectSource'](arg1, arg2, arg3, arg4);
}

export function BroadcastCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['BroadcastCommand'](arg1, arg2, arg3);
}

export function BroadcastRaw(arg1) {
  return window['go']['main']['App']['BroadcastRaw'](arg1);
}

export function CancelAuthChallenge(arg1) {
  return window['go']['main']['App']['CancelAuthChallenge'](arg1);
}

export function CancelBroadcast(arg1) {
  return window['go']['main']['App']['CancelBroadcast'](arg1);
}

export function CheckSSHAgent() {
  return window['go']['main']['App']['CheckSSHAgent']();
}

export function ClassifyConnectionError(arg1) {
  return window['go']['main']['App']['ClassifyConnectionError'](arg1);
}

export function ClearAuditLogs() {
  return window['go']['main']['App']['ClearAuditLogs']();
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function CloseWorkspacePane(arg1) {
  return window['go']['main']['App']['CloseWorkspacePane'](arg1);
}

export function ConfigureFolder(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConfigureFolder'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteKnownHost(arg1, arg2) {
  return window['go']['main']['App']['DeleteKnownHost'](arg1, arg2);
}

export function DeleteMacro(arg1) {
  return window['go']['main']['App']['DeleteMacro'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function DeleteSavedPassword(arg1) {
  return window['go']['main']['App']['DeleteSavedPassword'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function DuplicateFolder(arg1) {
  return window['go']['main']['App']['DuplicateFolder'](arg1);
}

export function DuplicateSession(arg1) {
  return window['go']['main']['App']['DuplicateSession'](arg1);
}

export function ExecuteMacro(arg1, arg2) {
  return window['go']['main']['App']['ExecuteMacro'](arg1, arg2);
}

export function ExecuteMulti(arg1, arg2) {
  return window['go']['main']['App']['ExecuteMulti'](arg1, arg2);
}

export function ExpandAllFolders(arg1) {
  return window['go']['main']['App']['ExpandAllFolders'](arg1);
}

export function ExportAuditLogsCSV() {
  return window['go']['main']['App']['ExportAuditLogsCSV']();
}

export function ExportAuditLogsJSON() {
  return window['go']['main']['App']['ExportAuditLogsJSON']();
}

export function ExportSessions() {
  return window['go']['main']['App']['ExportSessions']();
}

export function ExportSessionsToFile() {
  return window['go']['main']['App']['ExportSessionsToFile']();
}

export function FindSessionPassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FindSessionPassword'](arg1, arg2, arg3, arg4);
}

export function FocusWorkspacePane(arg1) {
  return window['go']['main']['App']['FocusWorkspacePane'](arg1);
}

export function GetAuditLogs(arg1) {
  return window['go']['main']['App']['GetAuditLogs'](arg1);
}

export function GetAvailableSerialPorts() {
  return window['go']['main']['App']['GetAvailableSerialPorts']();
}

export function GetCustomizerConfig() {
  return window['go']['main']['App']['GetCustomizerConfig']();
}

export function GetKnownHosts() {
  return window['go']['main']['App']['GetKnownHosts']();
}

export function GetMacros() {
  return window['go']['main']['App']['GetMacros']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetSavedPassword(arg1) {
  return window['go']['main']['App']['GetSavedPassword'](arg1);
}

export function GetSavedPasswords() {
  return window['go']['main']['App']['GetSavedPasswords']();
}

export function GetSecurityPolicy() {
  return window['go']['main']['App']['GetSecurityPolicy']();
}

export function GetSessionPassphrase(arg1) {
  return window['go']['main']['App']['GetSessionPassphrase'](arg1);
}

export function GetSessionPassword(arg1) {
  return window['go']['main']['App']['GetSessionPassword'](arg1);
}

export function GetSessionTree() {
  return window['go']['main']['App']['GetSessionTree']();
}

export function GetTunnels() {
  return window['go']['main']['App']['GetTunnels']();
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function HasSavedPassword(arg1) {
  return window['go']['main']['App']['HasSavedPassword'](arg1);
}

export function ImportSessions(arg1) {
  return window['go']['main']['App']['ImportSessions'](arg1);
}

export function ImportSessionsFromFile() {
  return window['go']['main']['App']['ImportSessionsFromFile']();
}

export function IsXServerRunning() {
  return window['go']['main']['App']['IsXServerRunning']();
}

export function LaunchRDPSession(arg1, arg2) {
  return window['go']['main']['App']['LaunchRDPSession'](arg1, arg2);
}

export function LaunchSystemTool(arg1) {
  return window['go']['main']['App']['LaunchSystemTool'](arg1);
}

export function LaunchXServer() {
  return window['go']['main']['App']['LaunchXServer']();
}

export function MoveNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveNode'](arg1, arg2, arg3);
}

export function MoveSession(arg1, arg2) {
  return window['go']['main']['App']['MoveSession'](arg1, arg2);
}

export function MoveWorkspaceTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveWorkspaceTab'](arg1, arg2, arg3);
}

export function NetCalculateHash(arg1, arg2) {
  return window['go']['main']['App']['NetCalculateHash'](arg1, arg2);
}

export function NetLookupDNS(arg1) {
  return window['go']['main']['App']['NetLookupDNS'](arg1);
}

export function NetPing(arg1) {
  return window['go']['main']['App']['NetPing'](arg1);
}

export function NetPortScan(arg1, arg2) {
  return window['go']['main']['App']['NetPortScan'](arg1, arg2);
}

export function OpenLocalTerminal(arg1) {
  return window['go']['main']['App']['OpenLocalTerminal'](arg1);
}

export function OpenSession(arg1, arg2) {
  return window['go']['main']['App']['OpenSession'](arg1, arg2);
}

export function OpenSessionLogFolder() {
  return window['go']['main']['App']['OpenSessionLogFolder']();
}

export function OpenSessionWithTabID(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenSessionWithTabID'](arg1, arg2, arg3);
}

export function OpenSessionWithTabIDAndJumpSecret(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenSessionWithTabIDAndJumpSecret'](arg1, arg2, arg3, arg4);
}

export function QuickConnect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['QuickConnect'](arg1, arg2, arg3, arg4, arg5);
}

export function RenameNode(arg1, arg2) {
  return window['go']['main']['App']['RenameNode'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RespondAuthChallenge(arg1, arg2) {
  return window['go']['main']['App']['RespondAuthChallenge'](arg1, arg2);
}

export function RespondHostKey(arg1, arg2) {
  return window['go']['main']['App']['RespondHostKey'](arg1, arg2);
}

export function RunSSHCommand(arg1, arg2) {
  return window['go']['main']['App']['RunSSHCommand'](arg1, arg2);
}

export function SFTPChmodLocal(arg1, arg2) {
  return window['go']['main']['App']['SFTPChmodLocal'](arg1, arg2);
}

export function SFTPChmodRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPChmodRemote'](arg1, arg2, arg3);
}

export function SFTPCommitExternalChange(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPCommitExternalChange'](arg1, arg2, arg3);
}

export function SFTPCreateFile(arg1, arg2) {
  return window['go']['main']['App']['SFTPCreateFile'](arg1, arg2);
}

export function SFTPCreateFileLocal(arg1) {
  return window['go']['main']['App']['SFTPCreateFileLocal'](arg1);
}

export function SFTPDelete(arg1, arg2) {
  return window['go']['main']['App']['SFTPDelete'](arg1, arg2);
}

export function SFTPDeleteLocal(arg1) {
  return window['go']['main']['App']['SFTPDeleteLocal'](arg1);
}

export function SFTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPDownload'](arg1, arg2, arg3);
}

export function SFTPGetFileProperties(arg1, arg2) {
  return window['go']['main']['App']['SFTPGetFileProperties'](arg1, arg2);
}

export function SFTPGetLocalDrives() {
  return window['go']['main']['App']['SFTPGetLocalDrives']();
}

export function SFTPList(arg1, arg2) {
  return window['go']['main']['App']['SFTPList'](arg1, arg2);
}

export function SFTPListLocal(arg1) {
  return window['go']['main']['App']['SFTPListLocal'](arg1);
}

export function SFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdir'](arg1, arg2);
}

export function SFTPMkdirLocal(arg1) {
  return window['go']['main']['App']['SFTPMkdirLocal'](arg1);
}

export function SFTPOpenExternal(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPOpenExternal'](arg1, arg2, arg3);
}

export function SFTPReadFile(arg1, arg2) {
  return window['go']['main']['App']['SFTPReadFile'](arg1, arg2);
}

export function SFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPRename'](arg1, arg2, arg3);
}

export function SFTPRenameLocal(arg1, arg2) {
  return window['go']['main']['App']['SFTPRenameLocal'](arg1, arg2);
}

export function SFTPUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUpload'](arg1, arg2, arg3);
}

export function SFTPWriteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPWriteFile'](arg1, arg2, arg3);
}

export function SaveCustomizerConfig(arg1) {
  return window['go']['main']['App']['SaveCustomizerConfig'](arg1);
}

export function SaveMacro(arg1) {
  return window['go']['main']['App']['SaveMacro'](arg1);
}

export function SavePassword(arg1, arg2) {
  return window['go']['main']['App']['SavePassword'](arg1, arg2);
}

export function SaveSecurityPolicy(arg1) {
  return window['go']['main']['App']['SaveSecurityPolicy'](arg1);
}

export function SaveSessionPassword(arg1, arg2) {
  return window['go']['main']['App']['SaveSessionPassword'](arg1, arg2);
}

export function SaveTerminalOutput(arg1, arg2) {
  return window['go']['main']['App']['SaveTerminalOutput'](arg1, arg2);
}

export function SaveTunnel(arg1) {
  return window['go']['main']['App']['SaveTunnel'](arg1);
}

export function SelectDownloadDest(arg1) {
  return window['go']['main']['App']['SelectDownloadDest'](arg1);
}

export function SelectPrivateKeyFile() {
  return window['go']['main']['App']['SelectPrivateKeyFile']();
}

export function SelectUploadFile() {
  return window['go']['main']['App']['SelectUploadFile']();
}

export function SetWorkspaceActiveTab(arg1, arg2) {
  return window['go']['main']['App']['SetWorkspaceActiveTab'](arg1, arg2);
}

export function SetWorkspaceLayout(arg1) {
  return window['go']['main']['App']['SetWorkspaceLayout'](arg1);
}

export function StartTunnel(arg1, arg2) {
  return window['go']['main']['App']['StartTunnel'](arg1, arg2);
}

export function StopSessionLog(arg1) {
  return window['go']['main']['App']['StopSessionLog'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function ToggleFolder(arg1, arg2) {
  return window['go']['main']['App']['ToggleFolder'](arg1, arg2);
}

export function UpdateFolder(arg1, arg2) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2);
}

export function UpdateSession(arg1) {
  return window['go']['main']['App']['UpdateSession'](arg1);
}

export function ValidatePrivateKeyFile(arg1, arg2) {
  return window['go']['main']['App']['ValidatePrivateKeyFile'](arg1, arg2);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
